OdeToFood/Models/CuisineType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Models
{
	public enum CuisineType
	{
		None,
		Italian,
		French,
		German
	}
}

OdeToFood/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Models
{
	public class Restaurant
	{
		public int Id { get; set; }

		[Display(Name="Restaurant Name")]
		[Required, MaxLength(80)]
		public string Name { get; set; }

		public CuisineType Cuisine { get; set; }
	}
}

OdeToFood/ViewModels/HomeIndexViewModel.cs
using OdeToFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewModels
{
	public class HomeIndexViewModel
	{
		public IEnumerable<Restaurant> Restaurants { get; set; }
		public string CurentMessage { get; set; }
	}
}

OdeToFood/ViewModels/RestaurantEditModel.cs
using OdeToFood.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewModels
{
	public class RestaurantEditModel
	{
		[Required, MaxLength(80)]
		public string Name { get; set; }
		public CuisineType Cuisine { get; set; }
	}
}

OdeToFood/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Controllers
{
	[Route("about")]
	public class AboutController
	{

		public string Phone()
		{
			return "1+555+555+5555";
		}

		public string Address()
		{
			return "USA";
		}
	}
}

OdeToFood/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Models;
using OdeToFood.Services;
using OdeToFood.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Controllers
{
	[Authorize]
	public class HomeController : Controller
	{
		private IRestaurantData _restaurantData;
		private IGreeter _greeter;

		public HomeController(IRestaurantData restaurantData,
							  IGreeter greeter)
		{
			_restaurantData = restaurantData;
			_greeter = greeter;
		}

		[AllowAnonymous]
		public IActionResult Index()
		{
			var model = new HomeIndexViewModel();
			model.Restaurants = _restaurantData.GetAll();
			model.CurentMessage = _greeter.GetMessageOfTheDay();

			return View(model);
		}

		public IActionResult Details(int id)
		{
			var model = _restaurantData.Get(id);

			if (model == null)
			{
				return RedirectToAction(nameof(Index));
			}

			return View(model);
		} 

		[HttpGet]
		public IActionResult Create()
		{

			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(RestaurantEditModel model)
		{
			if (ModelState.IsValid)
			{
				var newRestaurant = new Restaurant();
				newRestaurant.Name = model.Name;
				newRestaurant.Cuisine = model.Cuisine;

				newRestaurant = _restaurantData.Add(newRestaurant);

				return RedirectToAction(nameof(Details), new { id = newRestaurant.Id });
			}
			else
			{
				return View();
			}

			
		}
	}
}

OdeToFood/Pages/Greeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages
{
    public class GreetingModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Models;
using OdeToFood.Services;

namespace OdeToFood.Pages.Restaurants
{
	[Authorize]
    public class EditModel : PageModel
    {
		private IRestaurantData _restaurantData;

		[BindProperty]
		public Restaurant Restaurant { get; set; }

		public EditModel(IRestaurantData restaurantData)
		{
			_restaurantData = restaurantData;
		}

        public IActionResult OnGet(int id)
        {
			Restaurant = _restaurantData.Get(id);
			if (Restaurant == null)
			{
				return RedirectToAction("Index", "Home");
			}
			return Page();
        }

		public IActionResult OnPost()
		{
			if (ModelState.IsValid)
			{
				_restaurantData.Update(Restaurant);
				return RedirectToAction("Details", "Home", new { id = Restaurant.Id });
			}
			return Page();
		}
    }
}

OdeToFood/ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
	public class GreeterViewComponent : ViewComponent
	{
		private IGreeter _greeter;

		public GreeterViewComponent(IGreeter greeter)
		{
			_greeter = greeter;
		}

		public IViewComponentResult Invoke()
		{
			var model = _greeter.GetMessageOfTheDay();
			return View("Default", model);
		}
	}
}

OdeToFood/Pages/Greeting.cshtml
@page

@inject IGreeter Greeter

<div>@Greeter.GetMessageOfTheDay()</div>

OdeToFood/Pages/Restaurants/Edit.cshtml
@page "{id}"
@using OdeToFood.Pages.Restaurants

@model EditModel

<h1>Edit @Model.Restaurant.Name</h1>

<form method="post">

	<input type="hidden" asp-for="Restaurant.Id" />

	<!--El tag helper asp-for rellena automaticamente el html del
		input y del select con los datos del modelo actual-->
	<div>
		<label asp-for="Restaurant.Name"></label>
		<input asp-for="Restaurant.Name" />
		<span asp-validation-for="Restaurant.Name"></span>
	</div>

	<label asp-for="Restaurant.Cuisine"></label>
	<select asp-for="Restaurant.Cuisine" asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
	<span asp-validation-for="Restaurant.Cuisine"></span>

	<input type="submit" name="save" value="Save" />


</form>

OdeToFood/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
	<footer>
		@RenderSection("footer", required:false)
	</footer>
</body>
</html>

OdeToFood/Views/Home/Create.cshtml
@using OdeToFood.Models
@model Restaurant

@{ 
	ViewBag.Title = "Create";
}

<h1>Create</h1>

<form method="post">

	<!--El tag helper asp-for rellena automaticamente el html del 
		input y del select con los datos del modelo actual-->
	<div>
		<label asp-for="Name"></label>
		<input asp-for="Name" />
		<span asp-validation-for="Name"></span>
	</div>

	<label asp-for="Cuisine"></label>
	<select asp-for="Cuisine" asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
	<span asp-validation-for="Cuisine"></span>

	<input type="submit" name="save" value="Save" />


</form>
<div></div>

OdeToFood/Views/Home/Details.cshtml
@model Restaurant

@{ 
	ViewBag.Title = Model.Name;
}

<h1>@Model.Name</h1>

<div>
	Id: @Model.Id
</div>
<div>
	Cuisine: @Model.Cuisine
</div>

<a asp-action="Index" asp-controller="Home">Home</a>

OdeToFood/Views/Home/Index.cshtml
@model OdeToFood.ViewModels.HomeIndexViewModel

@{
	ViewBag.Title = "Home page";
}

<h1>All restaurants</h1>

@foreach (var restaurant in Model.Restaurants)
{
	@Html.Partial("_Summary", restaurant)
}

<div>
	<a class="btn btn-success" asp-action="Create">Add Restaurant</a>
</div>

OdeToFood/Views/Home/_Summary.cshtml
@model Restaurant

<div class="panel panel-primary">
	<h3 class="panel-heading">@Model.Name</h3>
	<div class="panel-body">
		Cuisine: @Model.Cuisine
	</div>
	<div class="panel-footer">
		<a class="btn btn-primary" asp-action="Details" asp-route-id="@Model.Id">More</a>
		<a class="btn btn-info" asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a>
	</div>
</div>

OdeToFood/Views/Shared/Components/Greeter/Default.cshtml
@model string

<div>
	@Model	
</div>

OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<environment include="Development">
		<link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
	</environment>

	<environment exclude="Development">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
				asp-fallback-href="~/node_modules/bootstrap/dist/css/bootstrap.css"
				asp-fallback-test-class="sr-only" asp-fallback-test-property="position"
				asp-fallback-test-value="absolute"/>
	</environment>

</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">OdeToFood</a>
			</div>
		</div>
	</nav>

	<div class="container">

		@RenderBody()
		<footer>
			@RenderSection("footer", required: false)
			<!--<vc:greeter></vc:greeter>-->

		</footer>
	</div>

	<environment include="Development">
		<script src="~/node_modules/jquery/dist/jquery.js"></script>
		<script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
		<script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
	</environment>

	<environment exclude="Development">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
				integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
				asp-fallback-src="~/node_modules/jquery/dist/jquery.js"
				crossorigin="anonymous"></script>
		
	</environment>

</body>
</html>